<?xml version="1.0" encoding="utf-8"?><Database Name="BookCatalog" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BookCatalog.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ConsoleAppLINQ.Properties.Settings" SettingsPropertyName="BookCatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BookCategories" Member="BookCategories">
    <Type Name="BookCategories">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="BookCategories_Books" Member="Books" ThisKey="Id" OtherKey="Category" Type="Books" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Books">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookCategories_Books" Member="BookCategories" ThisKey="Category" OtherKey="Id" Type="BookCategories" IsForeignKey="true" />
    </Type>
  </Table>
</Database>